import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('.artifacts', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
page.on('pageerror', error => errors.push(error.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__coastline && document.querySelector('#loading').classList.contains('loaded'));
await page.waitForTimeout(750);
assert.equal(await page.evaluate(() => window.__coastline.rendering.camera.top), 82.5);
assert.match(await page.locator('#view').getAttribute('aria-label'), /Medium view/);
await page.screenshot({ path: '.artifacts/coastline-initial.png' });
await page.keyboard.down('KeyW');
await page.waitForFunction(() => window.__coastline.vehicle.speed > 8);
await page.keyboard.up('KeyW');
assert.equal(await page.evaluate(() => window.__coastline.started), true);
assert.ok(await page.locator('#welcome').evaluate(el => el.classList.contains('hidden')));
await page.keyboard.press('KeyP');
const pausedPosition = await page.evaluate(() => window.__coastline.vehicle.s);
await page.waitForTimeout(350);
assert.equal(await page.evaluate(() => window.__coastline.vehicle.s), pausedPosition);
assert.equal(await page.locator('#pause-overlay').isVisible(), true);
await page.getByRole('button', { name: 'Resume drive' }).click();
assert.equal(await page.evaluate(() => window.__coastline.paused), false);
await page.keyboard.press('KeyR'); await page.waitForFunction(() => !window.__coastline.changingJourney);
const reset = await page.evaluate(() => ({ speed: window.__coastline.vehicle.speed, u: window.__coastline.vehicle.u }));
assert.equal(reset.speed, 0); assert.equal(reset.u, 2.4);
await page.keyboard.down('ArrowDown');
await page.waitForFunction(() => window.__coastline.vehicle.speed < -2);
await page.keyboard.up('ArrowDown');
await page.keyboard.press('KeyR'); await page.waitForFunction(() => !window.__coastline.changingJourney);
const uBefore = await page.evaluate(() => window.__coastline.vehicle.u);
await page.keyboard.down('ArrowUp'); await page.keyboard.down('ArrowRight');
await page.waitForFunction(u => window.__coastline.vehicle.u > u + .4, uBefore);
await page.keyboard.up('ArrowUp'); await page.keyboard.up('ArrowRight');
await page.keyboard.press('KeyR'); await page.waitForFunction(() => !window.__coastline.changingJourney);
await page.keyboard.press('KeyP');
await page.waitForFunction(() => !document.querySelector('#pause-overlay').hidden);
await page.getByRole('button', { name: 'Turn sound on' }).click();
await page.waitForFunction(() => document.querySelector('#sound').getAttribute('aria-pressed') === 'true');
await page.getByRole('button', { name: 'Turn sound off' }).click();
await page.waitForFunction(() => document.querySelector('#sound').getAttribute('aria-pressed') === 'false');
await page.keyboard.press('KeyP');
await page.waitForFunction(() => document.querySelector('#pause-overlay').hidden);
await page.keyboard.press('KeyV');
await page.waitForFunction(() => window.__coastline.rendering.camera.top < 59);
assert.match(await page.locator('#view').getAttribute('aria-label'), /Close view/);
assert.equal(await page.evaluate(() => window.__coastline.rendering.camera.isOrthographicCamera), true);
await page.keyboard.press('KeyV');
await page.waitForFunction(() => window.__coastline.rendering.camera.top < 39);
assert.match(await page.locator('#view').getAttribute('aria-label'), /Extra close view/);
assert.equal(await page.evaluate(() => window.__coastline.rendering.camera.isOrthographicCamera), true);
await page.keyboard.press('KeyV');
assert.match(await page.locator('#view').getAttribute('aria-label'), /Third-person view/);
assert.equal(await page.evaluate(() => window.__coastline.rendering.camera.isPerspectiveCamera), true);
await page.screenshot({ path: '.artifacts/coastline-third-person.png' });
await page.keyboard.press('KeyV');
assert.match(await page.locator('#view').getAttribute('aria-label'), /First-person view/);
await page.waitForFunction(() => {
  const { rendering, vehicle } = window.__coastline;
  return rendering.camera.isPerspectiveCamera && rendering.camera.position.distanceTo(vehicle.car.position) < 3;
});
assert.equal(await page.evaluate(() => window.__coastline.vehicle.car.visible), true, 'render restores exterior visibility');
await page.screenshot({ path: '.artifacts/coastline-first-person.png' });
await page.keyboard.press('KeyV');
await page.waitForFunction(() => window.__coastline.rendering.camera.top > 113);
assert.match(await page.locator('#view').getAttribute('aria-label'), /Scenic view/);
await page.keyboard.press('KeyV');
await page.waitForFunction(() => Math.abs(window.__coastline.rendering.camera.top - 82.5) < .2);
assert.match(await page.locator('#view').getAttribute('aria-label'), /Medium view/);
// Crosses dozens of chunk boundaries, including floating-origin shifts.
const streaming = await page.evaluate(async () => {
  const a = window.__coastline; const records = [];
  for (const s of [400, 900, 1026, 2300, 5100, 10000, 20000, 19900, 240, -129]) {
    a.vehicle.s = s; a.vehicle.reset();
    await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    const { behind, ahead } = a.graphics.settings.chunks;
    records.push({ s, chunks: a.world.chunks.size, resident: behind + ahead + 1, geometries: a.rendering.renderer.info.memory.geometries, textures: a.rendering.renderer.info.memory.textures, origin: a.world.origin, carZ: a.vehicle.car.position.z });
  }
  a.vehicle.s = 215; a.vehicle.reset(); a.rendering.snap();
  return records;
});
// Streaming holds exactly the window the quality level asks for.
// Textures: three for scenery plus six fixed AO textures.
for (const record of streaming) { assert.equal(record.chunks, record.resident); assert.ok(record.geometries <= 185); assert.ok(record.textures <= 9); assert.ok(Math.abs(record.carZ) < 1030); }
await page.waitForTimeout(700);
await page.screenshot({ path: '.artifacts/coastline-driving.png' });
// Held input is released when the window loses focus.
await page.keyboard.down('KeyW');
await page.evaluate(() => window.dispatchEvent(new Event('blur')));
assert.equal(await page.evaluate(() => window.__coastline.paused), true);
assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
await page.keyboard.up('KeyW');
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
mobile.on('pageerror', error => errors.push(error.message));
await mobile.goto(process.env.TEST_URL || 'http://127.0.0.1:5173', { waitUntil: 'networkidle' });
await mobile.waitForFunction(() => window.__coastline && document.querySelector('#loading').classList.contains('loaded'));
await mobile.waitForTimeout(750);
assert.equal(await mobile.locator('.touch-controls').isVisible(), false);
await mobile.screenshot({ path: '.artifacts/coastline-mobile.png' });
await mobile.getByRole('button', { name: 'Let’s drive' }).tap();
const accelerate = mobile.getByRole('group', { name: 'Virtual joystick', exact: true });
const bounds = await accelerate.boundingBox();
const client = await mobile.context().newCDPSession(mobile);
await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 - 36 }] });
await mobile.waitForFunction(() => window.__coastline.vehicle.speed > 3);
await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
assert.equal(await mobile.evaluate(() => window.__coastline.input.state.forward), false);
await mobile.waitForFunction(() => window.__coastline.vehicle.speed === 0);
assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
await mobile.screenshot({ path: '.artifacts/coastline-mobile-driving.png' });
await mobile.locator('#reset').tap();
await mobile.locator('#view').tap();
await mobile.waitForFunction(() => window.__coastline.rendering.camera.top < 66);
const closeCar = await mobile.evaluate(() => {
  const a = window.__coastline;
  return a.vehicle.car.position.clone().project(a.rendering.camera).toArray();
});
assert.ok(Math.abs(closeCar[0]) < .95 && Math.abs(closeCar[1]) < .8, 'close view keeps the car inside the mobile viewport');
await mobile.screenshot({ path: '.artifacts/coastline-mobile-close.png' });
assert.deepEqual(errors, []);
const report = { passed: true, checks: ['WASD acceleration', 'arrow controls and reverse', 'steering', 'pause/resume', 'scene reset', 'audio toggle', 'orthographic views', 'bounded streaming at 20 km', 'GPU resource release', 'floating origin', 'lost-focus input release', 'mobile touch input', 'responsive layout', 'no browser errors'], streaming };
await writeFile('.artifacts/browser-report.json', JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
await browser.close();
