import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    localStorage.setItem('coastline-install-dismissed-v2', String(Date.now()));
    window.testPads = [];
    Object.defineProperty(navigator, 'getGamepads', { configurable: true, value: () => window.testPads });
  });
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173');
  await page.waitForFunction(() => window.__coastline && document.querySelector('#loading.loaded'));
  await page.waitForTimeout(700);
  assert.equal(await page.locator('.touch-controls').isVisible(), false, 'Driving controls stay hidden on the menu');
  const connect = () => page.evaluate(() => {
    window.testPads = [null, { index: 1, mapping: 'standard', connected: true, axes: [0, 0, 0, 0], buttons: Array.from({ length: 17 }, () => ({ pressed: false, value: 0 })) }];
  });
  const button = (index, value) => page.evaluate(({ index, value }) => { window.testPads[1].buttons[index] = { pressed: value > .5, value }; }, { index, value });
  const frames = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const press = async index => { await button(index, 1); await frames(); await button(index, 0); await frames(); };
  await connect();
  await page.waitForFunction(() => document.body.dataset.controller === 'true');
  assert.equal(await page.locator('.touch-controls').isVisible(), false);
  assert.equal(await page.locator('#welcome .menu-hint').count(), 0, 'the title screen carries no control help');
  assert.equal(await page.locator('.touch-hint').isVisible(), false);
  assert.equal(await page.locator('#fps-counter').isVisible(), false);
  await button(11, 1); await frames();
  await page.waitForFunction(() => /^\d+ FPS$/.test(document.querySelector('#fps-counter').textContent));
  assert.equal(await page.locator('#fps-counter').isVisible(), true, 'holding R3 toggles FPS only once');
  await button(11, 0); await frames(); await press(11);
  assert.equal(await page.locator('#fps-counter').isVisible(), false);
  await page.screenshot({ path: '.artifacts/controller-mobile.png' });
  await button(7, .75);
  await page.waitForFunction(() => window.__coastline.started && window.__coastline.vehicle.speed > 3);
  await page.evaluate(() => window.testPads[1].axes[0] = .6);
  await page.waitForFunction(() => window.__coastline.vehicle.steer > .2);
  await page.evaluate(() => window.testPads[1].axes[0] = 0);
  await button(7, 0); await frames();
  await page.keyboard.down('h'); await frames();
  await page.keyboard.down('h'); await frames();
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'true', 'holding H toggles only once');
  await page.keyboard.up('h');
  await page.waitForFunction(() => window.__coastline.vehicle.speed > 8);
  await press(12);
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'false', 'D-pad Up turns autodrive off');
  await press(12);
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'true', 'D-pad Up turns autodrive on');
  await button(6, .5); await frames();
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'false', 'manual braking takes control');
  assert.ok(await page.evaluate(() => window.__coastline.input.state.brake > 0), 'held brake remains active after takeover');
  await button(6, 0); await frames();
  await page.keyboard.press('h'); await frames();
  await page.keyboard.down('d'); await frames();
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'false', 'manual steering takes control');
  assert.equal(await page.evaluate(() => window.__coastline.input.state.right), true, 'held steering remains active after takeover');
  await page.keyboard.up('d'); await frames();
  // D-pad Up also toggles autodrive; that must not break the code.
  const konami = [12, 12, 13, 13, 14, 15, 14, 15, 1, 0];
  for (const index of konami) await press(index);
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.rainbow), true);
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.freeDriving), true, 'the code leaves free driving alone');
  const carColors = () => page.evaluate(() => {
    const colors = new Set();
    window.__coastline.vehicle.car.traverse(object => { if (object.isMesh) colors.add(object.material.color.getHexString()); });
    return [...colors].sort().join(' ');
  });
  const rainbowStart = await carColors();
  await page.waitForTimeout(250);
  assert.notEqual(await carColors(), rainbowStart, 'the paint cycles through the rainbow');
  for (const index of konami) await press(index);
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.rainbow), false);
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.freeDriving), true);
  await press(9); assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  await press(11);
  assert.equal(await page.locator('#fps-counter').textContent(), 'FPS: paused');
  await press(11);
  assert.equal(await page.locator('#fps-counter').isVisible(), false);
  await button(9, 1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false, 'holding Start must not toggle repeatedly');
  await button(9, 0); await frames();
  await press(2); assert.match(await page.locator('#view').getAttribute('aria-label'), /Extra close view/);
  await press(3); await page.waitForFunction(() => !window.__coastline.changingJourney);
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.speed), 0);
  await button(6, 1); await page.waitForFunction(() => window.__coastline.vehicle.speed < -1);
  await button(6, 0); await frames();
  for (const selector of ['#change-journey', '#view', '#reset', '#next-journey', '#pause']) {
    assert.equal(await page.locator(selector).isVisible(), false, `${selector} hides with a controller`);
  }
  await press(8);
  const position = await page.evaluate(() => window.__coastline.vehicle.s);
  await button(7, 1); await press(9); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.s), position);
  assert.equal(await page.locator('#journey-dialog').isVisible(), true);
  await page.locator('#close-journeys').tap(); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await button(7, 0); await frames(); await button(7, 1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), 1);
  await button(7, 0); await frames();
  await press(10); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), true, 'right stick press opens the garage');
  const focused = () => page.evaluate(() => document.activeElement?.dataset?.car ?? null);
  assert.equal(await focused(), 'auto');
  await press(15); await frames();
  const second = await focused();
  assert.ok(second && second !== 'auto', `right moves along the grid (${second})`);
  await press(14); await frames();
  assert.equal(await focused(), 'auto', 'left returns along the grid');
  await press(12); await frames();
  const swatch = await page.evaluate(() => document.activeElement?.dataset?.paint ?? null);
  assert.ok(swatch, 'up from the fleet reaches the paint chips');
  await press(0); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), true, 'painting keeps the garage open');
  const chosen = await page.evaluate(() => window.__coastline.paint ?? 'default');
  assert.equal(chosen, swatch, 'A applies the focused colour');
  await press(13); await frames();
  assert.equal(await focused(), 'auto', 'down returns to the fleet');
  await press(13); await frames();
  const below = await focused();
  assert.ok(below && below !== 'auto', `down leaves the first row (${below})`);
  await press(13); await frames();
  const lower = await focused();
  assert.notEqual(lower, below, 'down keeps moving by row');
  const drop = await page.evaluate(([a, b]) => {
    const top = id => document.querySelector(`[data-car="${id}"]`).getBoundingClientRect().top;
    return top(b) - top(a);
  }, [below, lower]);
  assert.ok(drop > 1, `down moves to a later row (${drop}px)`);
  await press(12); await frames();
  assert.equal(await focused(), below, 'up returns to the row above');
  const garageStart = await page.evaluate(() => window.__coastline.vehicle.s);
  await press(0); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), false, 'A selects a car and closes the garage');
  assert.equal(await page.evaluate(() => window.__coastline.carId), below);
  const rolled = Math.abs(await page.evaluate(() => window.__coastline.vehicle.s) - garageStart);
  assert.ok(rolled < 5, `choosing a car keeps the place, not a teleport (${rolled}m)`);
  await press(10); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), true);
  await press(1); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), false, 'B closes the garage');
  await page.evaluate(() => window.__coastline.chooseCar('auto')); await frames();
  await press(9); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  assert.equal(await page.locator('#pause-overlay').isVisible(), true);
  const focus = () => page.evaluate(() => document.activeElement?.id || document.activeElement?.dataset?.quality || null);
  assert.equal(await focus(), 'resume', 'the pause screen opens on Resume');
  await press(13); await frames();
  assert.equal(await focus(), 'change-car', 'down reaches the garage button');
  await press(13); await frames();
  assert.equal(await focus(), 'autodrive', 'down reaches the autodrive switch');
  await press(0); await frames();
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  const autoStart = await page.evaluate(() => window.__coastline.vehicle.s);
  await frames();
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.s), autoStart, 'enabling autodrive keeps the simulation paused');
  await press(9);
  await page.waitForFunction(s => window.__coastline.vehicle.s > s + 1, autoStart);
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'true', 'autodrive resumes with the drive');
  await press(9);
  for (let step = 0; step < 2; step++) { await press(13); await frames(); }
  assert.equal(await focus(), 'autodrive');
  await press(0); await frames();
  assert.equal(await page.locator('#autodrive').getAttribute('aria-pressed'), 'false');
  await press(13); await frames();
  assert.equal(await focus(), 'traffic', 'down reaches the traffic switch');
  await press(0); await frames();
  assert.equal(await page.locator('#traffic').getAttribute('aria-pressed'), 'false');
  assert.equal(await page.evaluate(() => window.__coastline.traffic.group.visible), false);
  await press(0); await frames();
  assert.equal(await page.locator('#traffic').getAttribute('aria-pressed'), 'true');
  await press(13); await frames();
  assert.equal(await focus(), 'sound', 'down reaches the sound switch');
  await press(13); await frames();
  assert.equal(await focus(), 'audio-mixer-toggle', 'down reaches audio settings');
  await press(13); await frames();
  assert.equal(await focus(), 'fullscreen', 'down reaches the fullscreen switch');
  await press(13); await frames();
  assert.equal(await focus(), 'graphics-toggle', 'down reaches graphics settings');
  await press(0); await frames();
  assert.equal(await page.locator('#graphics-toggle').getAttribute('aria-expanded'), 'true');
  await press(13); await frames();
  const level = await page.evaluate(() => document.activeElement?.dataset?.quality ?? null);
  assert.ok(level, 'down reaches the graphics levels');
  await press(15); await frames();
  const nextLevel = await page.evaluate(() => document.activeElement?.dataset?.quality ?? null);
  assert.ok(nextLevel && nextLevel !== level, `right steps along the graphics levels (${nextLevel})`);
  await press(0); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.graphics.mode), nextLevel, 'A sets the focused level');
  assert.equal(await page.evaluate(() => window.__coastline.paused), true, 'a setting does not resume the drive');
  // Levels wrap to a second row on narrow screens, so walk down until found.
  for (let step = 0; step < 4 && await focus() !== 'soft-shading'; step++) { await press(13); await frames(); }
  assert.equal(await focus(), 'soft-shading', 'down reaches the soft shading switch');
  const shading = await page.locator('#soft-shading').getAttribute('aria-pressed');
  await press(0); await frames();
  assert.notEqual(await page.locator('#soft-shading').getAttribute('aria-pressed'), shading, 'A flips soft shading');
  await press(12); await frames();
  assert.equal(await focus(), 'pixel-density', 'up reaches pixel density');
  await press(12); await frames();
  assert.ok(await page.evaluate(() => document.activeElement?.dataset?.quality ?? null), 'up returns to the levels above');
  await press(10); await frames();
  assert.equal(await page.locator('#car-dialog').isVisible(), true, 'the garage still opens from the pause screen');
  await press(1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), true, 'closing the garage returns to the pause screen');
  assert.equal(await focus(), 'resume');
  await press(1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), false, 'B resumes from the pause screen');
  await page.evaluate(() => window.__coastline.graphics.setMode('auto')); await frames();
  await button(7, 1); await frames();
  await page.evaluate(() => { window.testPads = []; });
  await page.waitForFunction(() => document.body.dataset.controller === 'false');
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  assert.equal(await page.locator('.touch-controls').isVisible(), false, 'Driving controls stay hidden while paused');
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await connect(); await frames(); await press(9);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await button(7, 1); await frames();
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await button(7, 0); await frames(); await press(9);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await page.evaluate(() => { window.testPads = []; }); await frames();
  await page.locator('#resume').tap();
  assert.equal(await page.locator('.touch-controls').isVisible(), true);
  await page.keyboard.down('w');
  await page.waitForFunction(() => window.__coastline.vehicle.speed > 3);
  await page.keyboard.up('w');
  assert.deepEqual(errors, []);
  console.log('Controller detection, analog driving, reverse, shortcuts, menus, pause-screen navigation, garage grid and paint navigation, disconnect/reconnect, focus loss, touch visibility and keyboard fallback passed (simulated gamepad).');
} finally { await browser.close(); }
